version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
      dockerfile: dockerfile
    restart: on-failure
    networks:
      - wordpress-mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: "wordpress"
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - nginx-wordpress
      - wordpress-mariadb
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    networks:
      - nginx-wordpress
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env

networks:
  nginx-wordpress:
    driver: bridge
  wordpress-mariadb:
    driver: bridge

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sehjung/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sehjung/data/wordpress
