# 도커 컴포즈 파일의 버전
version: '3.8'

services:
  mariadb:
    restart: always # 컨테이너가 종료되면 항상 다시 시작하도록
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb
    expose: #컨테이너 내부의 포트 3306을 호스트 외부 포트에 노출시킨다.
      - '3306'
    volumes:
      - mariadb-volume:/var/lib/mysql # /home/jeongkpa/data/mariadb 디렉토리를 /var/lib/mysql에 매핑.
    networks: # 도커 네트워크 설정
      - intra-network
    env_file: # 환경 변수 파일
      - .env

  # 워드프레스는 마리아 디비 서비스에 데이터베이스를 쓰기 위해 의존한다.
  # 따라서 마리아디비 서비스가 먼저 시작돼야, 워드프레스 서비스가 정상적으로 동작할 수 있다.
  wordpress: # 컨테이너
    depends_on: # 마리아디비가 시작된 이후에 서비스가 시작되도록 지정.
      - mariadb
    restart: always # always: 컨테이너를 수동으로 끄기전까지 항상 재시작 됩니다.
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress
    expose:
      - '9000'
    volumes:
      - wordpress-volume:/var/www/html/wordpress # /home/jeongkpa/data/wordpress 디렉토리를 /var/www/html/wordpress에 맵핑
    networks:
      - intra-network
    env_file:
      - .env

  nginx: # 컨테이너
    depends_on:
      - wordpress
    restart: always # always: 컨테이너를 수동으로 끄기전까지 항상 재시작 됩니다.
    build: requirements/nginx
    container_name: nginx
    image: nginx
    ports: # port로 명시한 부분이 바로 host와 연결하는 부분이다. 모든 서비스는 이 port를 통해 접속 가능함.
      - '443:443'
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    networks:
      - intra-network
    env_file:
      - .env

networks:
  intra-network: # 네트워크 이름
    driver: bridge # Default 네트워크 드라이버
    name: intra-network
    # bridge networks are best when you need multiple containers to communicate on the same Docker host.

volumes:
  mariadb-volume: # volume 이름
    driver: local
    driver_opts:
      type: none
      o: bind # bind-mount을 사용해서, host의 file-system을 volume으로 사용한다.
      device: /home/sehjung/data/mariadb # 이건 linux에서 사용할 volume 경로 ( Subject 명시 )
  wordpress-volume: # volume 이름
    driver: local
    driver_opts:
      type: none
      o: bind # bind-mount을 사용해서, host의 file-system을 volume으로 사용한다.
      device: /home/sehjung/data/wordpress # ? 이건 linux에서 사용할 volume 경로 ( Subject 명시 )
