
all:
	$(GETNEXTLINE)
	arch -x86_64 gcc -L./mlx -lmlx -framework OpenGL -framework AppKit main.c put_image.c read_file.c get_next_line/get_next_line.c get_next_line/get_next_line_utils.c libft/libft.a
	./a.out